"""제철장보기 품목 목록.

- name: KAMIS 품목명 (코드는 코드표에서 이름으로 찾는다)
- vrty: 쓸 품종 코드 (None 이면 그때 조사된 품종 전부)
- grd: 쓸 등급 이름 (없으면 '상품' 등급이 있을 때 그것만)
- months: 제철로 보여 줄 달
- pick / keep: 고르는 법 / 보관법 (짧고 실용적인 것만)

제철 시기는 농식품부 식품나라 '이달의 제철 농산물'과 해양수산부 '이달의 수산물'을 기준으로,
KAMIS 에 소매가격이 조사되는 품목만 골랐다.
"""

CATS = {"채소": "🥬", "과일": "🍎", "축산": "🥩", "수산": "🐟", "곡물": "🌾"}

ITEMS = [
    # ── 채소 ──
    dict(key="cabbage", label="배추", name="배추", cat="채소", emoji="🥬", months=[10, 11, 12],
         pick="들었을 때 묵직하고 겉잎이 진한 초록색인 것", keep="신문지에 싸서 세워 두면 오래가요"),
    dict(key="radish", label="무", name="무", cat="채소", emoji="🥕", months=[10, 11, 12, 1],
         pick="껍질이 매끈하고 위쪽 초록 부분이 넓은 것", keep="잎을 잘라 내고 신문지에 싸서 서늘한 곳에"),
    dict(key="carrot", label="당근", name="당근", cat="채소", emoji="🥕", vrty=["00", "01"], months=[10, 11, 12],
         pick="주황색이 진하고 표면에 갈라짐이 없는 것", keep="물기를 닦고 키친타월에 싸서 냉장"),
    dict(key="redpepper", label="홍고추", name="붉은고추", cat="채소", emoji="🌶️", months=[8, 9, 10],
         pick="색이 고르게 붉고 꼭지가 싱싱한 것", keep="꼭지를 떼고 물기 없이 밀폐해 냉장, 오래 두려면 냉동"),
    dict(key="cabbage2", label="양배추", name="양배추", cat="채소", emoji="🥬", months=[3, 4, 5, 6],
         pick="들었을 때 묵직하고 겉잎이 연두색으로 윤기 있는 것", keep="심을 도려내고 젖은 키친타월을 채워 랩으로 싸서 냉장"),
    dict(key="spinach", label="시금치", name="시금치", cat="채소", emoji="🥬", months=[11, 12, 1, 2, 3],
         pick="잎이 두껍고 뿌리 쪽이 붉은빛인 것", keep="젖은 키친타월에 싸서 세워서 냉장"),
    dict(key="broccoli", label="브로콜리", name="브로콜리", item="280", cat="채소", emoji="🥦", months=[11, 12, 1, 2],
         pick="송이가 단단하고 꽃봉오리가 촘촘한 것", keep="비닐에 넣어 냉장, 오래 두려면 데쳐서 냉동"),
    dict(key="greenonion", label="대파", name="파", vrty=["00"], cat="채소", emoji="🌱", months=[11, 12, 1, 2],
         pick="흰 부분이 길고 단단한 것", keep="잘라서 키친타월 깐 통에 담아 냉장"),
    dict(key="chive", label="쪽파", name="파", vrty=["02"], cat="채소", emoji="🌱", months=[10, 11],
         pick="잎 끝이 마르지 않고 알뿌리가 통통한 것", keep="다듬어서 키친타월에 싸서 냉장"),
    dict(key="ginger", label="생강", name="생강", vrty=["00"], cat="채소", emoji="🫚", months=[10, 11],
         pick="통통하고 껍질이 얇으며 상처가 없는 것", keep="껍질째 키친타월에 싸서 냉장, 갈아서 냉동해도 좋아요"),
    dict(key="onion", label="양파", name="양파", vrty=["00", "02"], cat="채소", emoji="🧅", months=[5, 6],
         pick="껍질이 잘 마르고 단단한 것", keep="망에 넣어 바람이 잘 통하는 곳에"),
    dict(key="zucchini", label="애호박", name="호박", vrty=["01"], cat="채소", emoji="🥒", months=[6, 7, 8, 9],
         pick="꼭지가 마르지 않고 굵기가 고른 것", keep="하나씩 랩으로 싸서 냉장"),
    dict(key="cucumber", label="오이", name="오이", cat="채소", emoji="🥒", months=[5, 6, 7],
         pick="굵기가 고르고 가시가 살아 있는 것", keep="키친타월에 싸서 세워서 냉장"),
    dict(key="tomato", label="토마토", name="토마토", cat="채소", emoji="🍅", months=[5, 6, 7],
         pick="꼭지가 싱싱하고 고르게 붉은 것", keep="꼭지를 아래로 두고 상온에서 익힌 뒤 냉장"),
    dict(key="strawberry", label="딸기", name="딸기", cat="과일", emoji="🍓", months=[12, 1, 2, 3, 4],
         pick="꼭지가 싱싱하고 끝까지 붉은 것", keep="씻지 않고 키친타월 깐 통에 담아 냉장"),
    dict(key="watermelon", label="수박", name="수박", cat="과일", emoji="🍉", months=[6, 7, 8],
         pick="두드리면 맑은 소리가 나고 줄무늬가 선명한 것", keep="잘랐으면 랩을 씌워 냉장"),
    dict(key="melon", label="참외", name="참외", cat="과일", emoji="🍈", months=[5, 6, 7],
         pick="노란색이 진하고 골이 깊은 것", keep="비닐에 넣어 냉장"),
    # ── 곡물 ──
    dict(key="sweetpotato", label="고구마", name="고구마", cat="곡물", emoji="🍠", months=[9, 10, 11],
         pick="껍질 색이 고르고 잔뿌리가 적은 것", keep="냉장 말고 신문지에 싸서 서늘한 실온에"),
    dict(key="potato", label="감자", name="감자", cat="곡물", emoji="🥔", months=[6, 7, 8],
         pick="싹이 나지 않고 껍질에 초록빛이 없는 것", keep="빛이 들지 않는 서늘한 곳에, 사과 한 개를 같이 두면 싹이 덜 나요"),
    # ── 과일 ──
    dict(key="apple", label="사과", name="사과", vrty=["05", "07"], cat="과일", emoji="🍎", months=[9, 10, 11, 12],
         pick="꼭지가 싱싱하고 들었을 때 묵직한 것", keep="하나씩 신문지에 싸서 냉장, 다른 과일과 따로"),
    dict(key="pear", label="배", name="배", vrty=["01"], cat="과일", emoji="🍐", months=[9, 10, 11],
         pick="껍질이 맑은 황갈색이고 묵직한 것", keep="하나씩 신문지에 싸서 냉장"),
    dict(key="persimmon", label="단감", name="단감", cat="과일", emoji="🟠", months=[10, 11],
         pick="꼭지가 붙어 있고 주황색이 고른 것", keep="꼭지를 아래로 두고 냉장"),
    dict(key="tangerine", label="감귤", name="감귤", cat="과일", emoji="🍊", months=[11, 12, 1, 2],
         pick="껍질이 얇고 꼭지가 작은 것", keep="서로 닿지 않게 펼쳐서 서늘한 곳에"),
    # KAMIS 소매 조사는 뉴질랜드산(그린)만 있다
    dict(key="kiwi", label="키위", name="참다래", vrty=["02"], cat="과일", emoji="🥝", months=[],
         pick="털이 고르고 상처가 없는 것", keep="단단하면 사과와 같이 두어 후숙한 뒤 냉장"),
    dict(key="cherry", label="체리", name="체리", cat="과일", emoji="🍒", months=[],
         pick="꼭지가 초록색이고 알이 단단하며 윤기 나는 것", keep="씻지 않고 밀폐 용기에 담아 냉장"),
    dict(key="peach", label="복숭아", name="복숭아", cat="과일", emoji="🍑", months=[7, 8],
         pick="향이 진하고 꼭지 쪽까지 색이 든 것", keep="상온에 두었다가 먹기 2시간 전에 냉장"),
    dict(key="shine", label="샤인머스켓", name="포도", vrty=["12"], cat="과일", emoji="🍇", months=[8, 9, 10],
         pick="알이 크고 연둣빛에 노란기가 살짝 도는 것", keep="송이째 키친타월에 싸서 냉장"),
    dict(key="campbell", label="캠벨포도", name="포도", vrty=["01"], cat="과일", emoji="🍇", months=[8, 9],
         pick="알이 단단하고 표면에 흰 가루가 고르게 있는 것", keep="씻지 않고 비닐에 넣어 냉장"),
    dict(key="kyoho", label="거봉", name="포도", vrty=["02"], cat="과일", emoji="🍇", months=[8, 9],
         pick="알이 굵고 꼭지 쪽까지 색이 짙은 것", keep="씻지 않고 비닐에 넣어 냉장"),
    # ── 버섯 ──
    dict(key="oyster", label="느타리버섯", name="느타리버섯", vrty=["00"], cat="채소", emoji="🍄", months=[9, 10, 11],
         pick="갓이 도톰하고 탄력 있는 것", keep="씻지 않고 키친타월에 싸서 냉장"),
    # ── 수산 ──
    dict(key="crab", label="꽃게", name="꽃게", vrty=["01", "04", "05"], cat="수산", emoji="🦀", months=[4, 5, 9, 10],
         pick="들었을 때 묵직하고 배 쪽이 단단한 것", keep="바로 먹지 않으면 손질해서 냉동"),
    dict(key="gizzardshad", label="전어", name="전어", cat="수산", emoji="🐟", months=[9, 10],
         pick="눈이 맑고 비늘이 반짝이는 것", keep="당일에 먹는 게 가장 좋아요"),
    dict(key="mackerel", label="고등어", name="고등어", vrty=["01", "05"], grd=["大"], cat="수산", emoji="🐟", months=[9, 10, 11],
         pick="등이 푸르고 배가 은빛으로 단단한 것", keep="내장을 빼고 소금을 살짝 뿌려 냉장"),
    dict(key="hairtail", label="갈치", name="갈치", vrty=["01", "03"], cat="수산", emoji="🐟", months=[8, 9, 10],
         pick="은빛 가루가 고르게 남아 있는 것", keep="토막 내어 하나씩 랩으로 싸서 냉동"),
    dict(key="spanishmackerel", label="삼치", name="삼치", cat="수산", emoji="🐟", months=[10, 11, 12, 1],
         pick="살이 단단하고 눈이 맑은 것", keep="토막 내어 하나씩 랩으로 싸서 냉동"),
    dict(key="oyster_sea", label="굴", name="굴", cat="수산", emoji="🦪", months=[11, 12, 1, 2],
         pick="우윳빛이 돌고 테두리가 검고 선명한 것", keep="소금물에 흔들어 씻어 냉장, 이틀 안에"),
    dict(key="mussel", label="홍합", name="홍합", vrty=["02"], cat="수산", emoji="🦪", months=[11, 12, 1, 2],
         pick="껍데기가 꽉 닫혀 있고 윤기 있는 것", keep="수염을 떼고 바로 조리하는 게 좋아요"),
    dict(key="squid", label="오징어", name="물오징어", vrty=["01", "03"], cat="수산", emoji="🦑", months=[9, 10, 11],
         pick="몸통이 투명하고 탄력 있는 것", keep="손질해서 한 번 먹을 만큼씩 냉동"),
    dict(key="clam", label="바지락", name="바지락", cat="수산", emoji="🐚", months=[3, 4, 5],
         pick="입이 꽉 닫혀 있고 두드리면 맑은 소리가 나는 것", keep="소금물에 해감한 뒤 바로 조리"),
    dict(key="scallop", label="홍가리비", name="가리비", cat="수산", emoji="🐚", months=[11, 12, 1, 2, 3],
         pick="껍데기가 닫혀 있거나 건드리면 바로 닫히는 것", keep="해감해서 바로 조리, 남으면 쪄서 살만 냉동"),
]

# 제철이 따로 없거나(months=[]) 수입품인 일상 장보기 품목
ITEMS += [
    # ── 채소 ──
    dict(key="lettuce_red", label="적상추", name="상추", vrty=["01"], cat="채소", emoji="🥬", months=[4, 5, 6],
         pick="잎이 연하고 끝이 시들지 않은 것", keep="젖은 키친타월을 깔고 밀폐 용기에 담아 냉장"),
    dict(key="lettuce_green", label="청상추", name="상추", vrty=["02"], cat="채소", emoji="🥬", months=[4, 5, 6],
         pick="잎이 연하고 끝이 시들지 않은 것", keep="젖은 키친타월을 깔고 밀폐 용기에 담아 냉장"),
    dict(key="perilla", label="깻잎", name="깻잎", cat="채소", emoji="🌿", months=[7, 8, 9],
         pick="향이 진하고 잎이 짙은 초록색인 것", keep="꼭지를 아래로 세워 물을 조금 담은 컵에 꽂아 냉장"),
    dict(key="chives", label="부추", name="부추", cat="채소", emoji="🌱", months=[3, 4, 5],
         pick="잎끝이 마르지 않고 곧게 선 것", keep="씻지 않고 키친타월에 싸서 냉장"),
    dict(key="napa_young", label="얼갈이배추", name="얼갈이배추", cat="채소", emoji="🥬", months=[5, 6],
         pick="잎이 연하고 줄기가 통통한 것", keep="신문지에 싸서 냉장"),
    dict(key="napa_baby", label="알배기배추", name="알배기배추", cat="채소", emoji="🥬", months=[],
         pick="속이 꽉 차 단단하고 묵직한 것", keep="겉잎째 랩으로 싸서 냉장"),
    dict(key="yeolmu", label="열무", name="열무", cat="채소", emoji="🥬", months=[5, 6, 7],
         pick="잎이 연하고 뿌리가 가는 것", keep="다듬어서 신문지에 싸서 냉장, 이틀 안에"),
    dict(key="eggplant", label="가지", name="가지", cat="채소", emoji="🍆", months=[6, 7, 8],
         pick="보랏빛이 진하고 윤기 나며 꼭지 가시가 날카로운 것", keep="하나씩 키친타월에 싸서 냉장"),
    dict(key="greenpepper", label="풋고추", name="풋고추", vrty=["00"], cat="채소", emoji="🫑", months=[6, 7, 8],
         pick="꼭지가 싱싱하고 껍질이 매끈한 것", keep="물기를 닦고 밀폐 용기에 담아 냉장"),
    dict(key="cheongyang", label="청양고추", name="풋고추", vrty=["03"], cat="채소", emoji="🌶️", months=[7, 8, 9],
         pick="꼭지가 싱싱하고 색이 진한 것", keep="꼭지를 떼고 냉동해 두면 오래 써요"),
    dict(key="shishito", label="꽈리고추", name="풋고추", vrty=["02"], cat="채소", emoji="🫑", months=[6, 7, 8],
         pick="주름이 고르고 연둣빛이 선명한 것", keep="물기를 닦고 밀폐 용기에 담아 냉장"),
    dict(key="cucumberpepper", label="오이고추", name="풋고추", vrty=["04"], cat="채소", emoji="🫑", months=[6, 7, 8],
         pick="통통하고 껍질에 윤기가 있는 것", keep="물기를 닦고 밀폐 용기에 담아 냉장"),
    dict(key="driedpepper", label="건고추", name="건고추", cat="채소", emoji="🌶️", months=[8, 9, 10],
         pick="색이 고르게 붉고 꼭지가 붙어 있는 것", keep="습기 없는 밀폐 용기에 담아 냉동"),
    dict(key="chilipowder", label="고춧가루", name="고춧가루", vrty=["00"], cat="채소", emoji="🌶️", months=[],
         pick="색이 선명하고 덩어리지지 않은 것", keep="지퍼백에 나눠 담아 냉동"),
    dict(key="garlic", label="깐마늘", name="깐마늘(국산)", vrty=["01"], cat="채소", emoji="🧄", months=[5, 6],
         pick="알이 단단하고 무른 곳이 없는 것", keep="키친타월을 깐 밀폐 용기에 담아 냉장, 다져서 냉동해도 좋아요"),
    dict(key="minari", label="미나리", name="미나리", cat="채소", emoji="🌿", months=[2, 3, 4],
         pick="줄기가 곧고 잎이 싱싱한 것", keep="젖은 키친타월에 싸서 냉장"),
    dict(key="greenbellpepper", label="피망", name="피망", cat="채소", emoji="🫑", months=[6, 7, 8],
         pick="껍질이 단단하고 꼭지가 싱싱한 것", keep="비닐에 넣어 냉장"),
    dict(key="paprika", label="파프리카", name="파프리카", cat="채소", emoji="🫑", months=[6, 7, 8],
         pick="색이 선명하고 묵직한 것", keep="하나씩 키친타월에 싸서 냉장"),
    dict(key="cherrytomato", label="방울토마토", name="방울토마토", vrty=["01"], cat="채소", emoji="🍅", months=[4, 5, 6],
         pick="꼭지가 싱싱하고 붉은색이 고른 것", keep="꼭지를 떼고 씻지 않은 채 냉장"),
    dict(key="datetomato", label="대추방울토마토", name="방울토마토", vrty=["02"], cat="채소", emoji="🍅", months=[4, 5, 6],
         pick="단단하고 껍질에 윤기가 있는 것", keep="꼭지를 떼고 씻지 않은 채 냉장"),
    dict(key="enoki", label="팽이버섯", name="팽이버섯", cat="채소", emoji="🍄", months=[],
         pick="갓이 작고 하얗며 물기가 없는 것", keep="봉지째 냉장, 쓰고 남은 건 랩으로 싸서"),
    dict(key="kingoyster", label="새송이버섯", name="새송이버섯", cat="채소", emoji="🍄", months=[],
         pick="기둥이 굵고 단단하며 갓이 펴지지 않은 것", keep="씻지 않고 키친타월에 싸서 냉장"),
    # ── 과일 ──
    dict(key="melon_fruit", label="멜론", name="멜론", cat="과일", emoji="🍈", months=[6, 7, 8],
         pick="그물 무늬가 고르고 꼭지 반대쪽을 누르면 살짝 들어가는 것", keep="익을 때까지 실온에 두었다가 냉장"),
    dict(key="banana", label="바나나", name="바나나", cat="과일", emoji="🍌", months=[],
         pick="껍질이 노랗고 꼭지 쪽이 살짝 초록빛인 것", keep="걸어 두거나 꼭지를 랩으로 싸서 실온에"),
    dict(key="pineapple", label="파인애플", name="파인애플", cat="과일", emoji="🍍", months=[],
         pick="향이 달고 잎이 쉽게 빠지지 않는 것", keep="잎을 아래로 거꾸로 세워 두면 단맛이 고르게 퍼져요"),
    dict(key="orange", label="오렌지", name="오렌지", cat="과일", emoji="🍊", months=[],
         pick="껍질이 얇고 묵직한 것", keep="비닐에 넣어 냉장"),
    dict(key="lemon", label="레몬", name="레몬", cat="과일", emoji="🍋", months=[],
         pick="껍질이 매끈하고 노란색이 진한 것", keep="비닐에 넣어 냉장, 즙을 짜서 얼려 두어도 좋아요"),
    dict(key="mango", label="망고", name="망고", cat="과일", emoji="🥭", months=[],
         pick="향이 진하고 살짝 눌렀을 때 탄력 있는 것", keep="익을 때까지 실온에 두었다가 냉장"),
    dict(key="blueberry", label="냉동 블루베리", name="블루베리", cat="과일", emoji="🫐", months=[],
         pick="알끼리 뭉쳐 얼지 않은 것", keep="녹았다 다시 얼면 물러지니 바로 냉동실에"),
    dict(key="avocado", label="아보카도", name="아보카도", cat="과일", emoji="🥑", months=[],
         pick="껍질이 짙은 갈색이고 살짝 눌렀을 때 들어가는 것", keep="단단하면 실온에서 익힌 뒤 냉장"),
    # ── 축산 ──
    dict(key="hanwoo_sirloin", label="한우 등심", name="소", item="4301", vrty=["22"], grd=["1+등급"], cat="축산", emoji="🥩", months=[],
         pick="선홍색이고 지방이 고르게 퍼져 있는 것", keep="한 번 먹을 만큼씩 랩으로 싸서 냉동"),
    dict(key="hanwoo_tenderloin", label="한우 안심", name="소", item="4301", vrty=["21"], grd=["1+등급"], cat="축산", emoji="🥩", months=[],
         pick="선홍색이고 결이 고운 것", keep="한 번 먹을 만큼씩 랩으로 싸서 냉동"),
    dict(key="hanwoo_brisket", label="한우 양지", name="소", item="4301", vrty=["40"], grd=["1+등급"], cat="축산", emoji="🥩", months=[],
         pick="선홍색이고 핏물이 고여 있지 않은 것", keep="국거리 크기로 썰어 나눠 냉동"),
    dict(key="hanwoo_round", label="한우 설도", name="소", item="4301", vrty=["36"], grd=["1+등급"], cat="축산", emoji="🥩", months=[],
         pick="선홍색이고 핏물이 고여 있지 않은 것", keep="한 번 먹을 만큼씩 랩으로 싸서 냉동"),
    dict(key="hanwoo_ribs", label="한우 갈비", name="소", item="4301", vrty=["50"], grd=["1+등급"], cat="축산", emoji="🍖", months=[],
         pick="뼈가 붉고 살이 두툼한 것", keep="핏물을 빼고 양념해 나눠 냉동"),
    dict(key="pork_belly", label="삼겹살", name="돼지", item="4304", vrty=["27"], cat="축산", emoji="🥓", months=[],
         pick="살코기와 지방 층이 고르고 분홍빛인 것", keep="한 번 먹을 만큼씩 랩으로 싸서 냉동"),
    dict(key="pork_neck", label="목살", name="돼지", item="4304", vrty=["68"], cat="축산", emoji="🥩", months=[],
         pick="분홍빛이고 지방이 고르게 박힌 것", keep="한 번 먹을 만큼씩 랩으로 싸서 냉동"),
    dict(key="pork_shoulder", label="앞다리살", name="돼지", item="4304", vrty=["25"], cat="축산", emoji="🥩", months=[],
         pick="분홍빛이고 핏물이 고여 있지 않은 것", keep="찌개용·수육용으로 나눠 냉동"),
    dict(key="pork_ribs", label="돼지갈비", name="돼지", item="4304", vrty=["28"], cat="축산", emoji="🍖", months=[],
         pick="살이 두툼하고 분홍빛인 것", keep="핏물을 빼고 양념해 나눠 냉동"),
    dict(key="imported_beef_ribs", label="수입 소갈비", name="수입 소고기", item="4401", vrty=["31"], grd=["미국산"], cat="축산", emoji="🍖",
         months=[], pick="선홍색이고 뼈에 살이 두툼하게 붙은 것", keep="핏물을 빼고 나눠 냉동"),
    dict(key="imported_beef_ribmeat", label="수입 갈비살", name="수입 소고기", item="4401", vrty=["37"], grd=["미국산"], cat="축산", emoji="🥩",
         months=[], pick="선홍색이고 지방이 고르게 박힌 것", keep="한 번 먹을 만큼씩 랩으로 싸서 냉동"),
    dict(key="imported_pork_belly", label="수입 삼겹살", name="수입 돼지고기", item="4402", vrty=["27"], cat="축산", emoji="🥓", months=[],
         pick="살코기와 지방 층이 고른 것", keep="한 번 먹을 만큼씩 랩으로 싸서 냉동"),
    dict(key="chicken", label="닭고기", name="닭", item="9901", vrty=["99"], cat="축산", emoji="🍗", months=[],
         pick="껍질이 크림색으로 윤기 있고 탄력 있는 것", keep="손질해서 이틀 안에 먹거나 냉동"),
    dict(key="egg", label="계란", name="계란", item="9903", vrty=["23"], grd=["일반란"], cat="축산", emoji="🥚", months=[],
         pick="껍데기가 깨끗하고 금이 가지 않은 것", keep="뾰족한 쪽을 아래로 해서 냉장"),
    dict(key="milk", label="우유", name="우유", item="9908", cat="축산", emoji="🥛", months=[],
         pick="유통기한이 넉넉한 것", keep="문 쪽보다 안쪽 칸에 냉장, 열면 빨리 마셔요"),
    # ── 수산 ──
    dict(key="salted_mackerel", label="자반고등어", name="고등어", vrty=["03"], cat="수산", emoji="🐟", months=[],
         pick="살이 단단하고 기름기가 도는 것", keep="한 손씩 랩으로 싸서 냉동"),
    dict(key="saury", label="꽁치", name="꽁치", cat="수산", emoji="🐟", months=[],
         pick="눈이 맑고 몸통이 단단한 것", keep="손질해서 하나씩 랩으로 싸서 냉동"),
    dict(key="croaker", label="참조기", name="조기", vrty=["06"], grd=["中"], cat="수산", emoji="🐟", months=[],
         pick="배가 노랗고 비늘이 붙어 있는 것", keep="하나씩 랩으로 싸서 냉동"),
    dict(key="gulbi", label="굴비", name="조기", vrty=["07"], cat="수산", emoji="🐟", months=[],
         pick="배가 노랗고 몸통이 통통한 것", keep="하나씩 랩으로 싸서 냉동"),
    dict(key="pollock", label="동태", name="명태", vrty=["04"], cat="수산", emoji="🐟", months=[],
         pick="살이 하얗고 냄새가 나지 않는 것", keep="녹였다 다시 얼리지 말고 바로 냉동"),
    dict(key="anchovy", label="마른멸치", name="마른멸치", cat="수산", emoji="🐟", months=[],
         pick="은빛이 돌고 몸통이 곧은 것", keep="지퍼백에 담아 냉동"),
    dict(key="driedsquid", label="마른오징어", name="마른오징어", cat="수산", emoji="🦑", months=[],
         pick="하얀 가루가 고르게 피고 두툼한 것", keep="지퍼백에 담아 냉동"),
    dict(key="laver", label="구운김", name="김", vrty=["01"], cat="수산", emoji="🍙", months=[11, 12, 1, 2],
         pick="검은빛에 윤기가 있고 구멍이 적은 것", keep="습기 없게 밀봉해 냉동"),
    dict(key="driedseaweed", label="마른미역", name="마른미역", cat="수산", emoji="🌿", months=[],
         pick="검푸른빛이 돌고 잘 마른 것", keep="습기 없는 곳에 밀봉"),
    dict(key="kelp", label="건다시마", name="건다시마", cat="수산", emoji="🌿", months=[],
         pick="두껍고 표면에 흰 가루가 고르게 핀 것", keep="습기 없는 곳에 밀봉"),
    dict(key="abalone", label="전복", name="전복", cat="수산", emoji="🐚", months=[],
         pick="만졌을 때 살이 움찔하고 움직이는 것", keep="젖은 키친타월을 덮어 냉장, 이틀 안에"),
    dict(key="shrimp", label="흰다리새우", name="새우", cat="수산", emoji="🦐", months=[],
         pick="껍데기가 투명하고 머리가 검게 변하지 않은 것", keep="손질해서 한 번 먹을 만큼씩 냉동"),
    dict(key="shrimpjeot", label="새우젓", name="새우젓", cat="수산", emoji="🦐", months=[],
         pick="새우 모양이 살아 있고 국물이 맑은 것", keep="밀폐 용기에 담아 냉장 또는 냉동"),
    dict(key="fishsauce", label="멸치액젓", name="멸치액젓", cat="수산", emoji="🫙", months=[],
         pick="색이 맑은 갈색인 것", keep="뚜껑을 꼭 닫아 서늘한 곳에"),
    dict(key="salt", label="천일염", name="천일염", cat="수산", emoji="🧂", months=[],
         pick="알갱이가 고르고 잘 마른 것", keep="습기 없는 곳에 밀봉"),
    # ── 곡물·견과 ──
    dict(key="rice", label="쌀", name="쌀", vrty=["10"], cat="곡물", emoji="🍚", months=[],
         pick="도정일이 최근이고 깨진 알이 적은 것", keep="밀폐 용기에 담아 서늘한 곳에, 여름엔 냉장"),
    dict(key="newrice", label="햅쌀", name="쌀", vrty=["11"], cat="곡물", emoji="🍚", months=[9, 10, 11],
         pick="도정일이 최근이고 깨진 알이 적은 것", keep="밀폐 용기에 담아 서늘한 곳에"),
    dict(key="glutinousrice", label="찹쌀", name="찹쌀", cat="곡물", emoji="🍚", months=[],
         pick="뽀얗고 알이 고른 것", keep="밀폐 용기에 담아 서늘한 곳에"),
    dict(key="mixedgrain", label="혼합곡", name="혼합곡", cat="곡물", emoji="🌾", months=[],
         pick="낟알이 고르고 이물질이 없는 것", keep="밀폐 용기에 담아 냉장"),
    dict(key="barley", label="찰보리쌀", name="보리쌀", cat="곡물", emoji="🌾", months=[],
         pick="낟알이 통통하고 고른 것", keep="밀폐 용기에 담아 서늘한 곳에"),
    dict(key="soybean", label="흰콩", name="콩", cat="곡물", emoji="🫘", months=[10, 11],
         pick="알이 굵고 껍질에 윤기가 있는 것", keep="밀폐 용기에 담아 서늘한 곳에"),
    dict(key="redbean", label="팥", name="팥", cat="곡물", emoji="🫘", months=[10, 11],
         pick="붉은빛이 진하고 알이 고른 것", keep="밀폐 용기에 담아 서늘한 곳에"),
    dict(key="mungbean", label="녹두", name="녹두", cat="곡물", emoji="🫘", months=[],
         pick="초록빛이 선명하고 알이 고른 것", keep="밀폐 용기에 담아 서늘한 곳에"),
    dict(key="sesame", label="참깨", name="참깨", vrty=["01"], cat="곡물", emoji="🌾", months=[9, 10],
         pick="알이 통통하고 껍질에 윤기가 있는 것", keep="밀폐해 냉동하면 고소한 맛이 오래가요"),
    dict(key="peanut", label="땅콩", name="땅콩", vrty=["01"], cat="곡물", emoji="🥜", months=[9, 10],
         pick="알이 굵고 껍질에 얼룩이 없는 것", keep="밀폐해 냉장"),
    dict(key="walnut", label="호두", name="호두", cat="곡물", emoji="🌰", months=[],
         pick="알이 밝은 색이고 기름 냄새가 나지 않는 것", keep="밀폐해 냉동"),
    dict(key="almond", label="아몬드", name="아몬드", cat="곡물", emoji="🌰", months=[],
         pick="알이 고르고 쩐내가 나지 않는 것", keep="밀폐해 서늘한 곳에"),
]

# 농식품부·aT 4인 가족 김장 비용 조사(배추 20포기) 기준 14개 품목과 수량
KIMJANG = [
    dict(key="kj_cabbage", label="배추", name="배추", qty=20, unit="포기", per="count"),
    dict(key="kj_radish", label="무", name="무", qty=5, unit="개", per="count"),
    dict(key="kj_chili", label="고춧가루", name="고춧가루", vrty=["00"], qty=2, unit="kg", per="kg"),
    dict(key="kj_garlic", label="깐마늘", name="깐마늘(국산)", vrty=["01"], qty=1.3, unit="kg", per="kg"),
    dict(key="kj_greenonion", label="대파", name="파", vrty=["00"], qty=0.7, unit="kg", per="kg"),
    dict(key="kj_chive", label="쪽파", name="파", vrty=["02"], qty=0.7, unit="kg", per="kg"),
    dict(key="kj_onion", label="양파", name="양파", vrty=["00", "02"], qty=0.8, unit="kg", per="kg"),
    dict(key="kj_ginger", label="생강", name="생강", vrty=["00"], qty=0.3, unit="kg", per="kg"),
    dict(key="kj_mustard", label="갓", name="갓", qty=1.4, unit="kg", per="kg"),
    dict(key="kj_minari", label="미나리", name="미나리", qty=0.4, unit="kg", per="kg"),
    dict(key="kj_pear", label="배", name="배", vrty=["01"], qty=3, unit="개", per="count"),
    dict(key="kj_salt", label="천일염", name="천일염", qty=6, unit="kg", per="kg"),
    dict(key="kj_shrimp", label="새우젓", name="새우젓", qty=0.8, unit="kg", per="kg"),
    dict(key="kj_anchovy", label="멸치액젓", name="멸치액젓", qty=1.2, unit="kg", per="kg"),
]
KIMJANG_SOURCE = "농림축산식품부·aT 4인 가족 김장 비용 조사 기준(배추 20포기)"

# 검색에 같이 걸리게 할 다른 이름 (예: '소고기'로 찾으면 한우 부위가 다 나온다)
ALIASES = {
    "소고기 쇠고기": ["hanwoo_sirloin", "hanwoo_tenderloin", "hanwoo_brisket", "hanwoo_round", "hanwoo_ribs",
                   "imported_beef_ribs", "imported_beef_ribmeat"],
    "돼지고기": ["pork_belly", "pork_neck", "pork_shoulder", "pork_ribs", "imported_pork_belly"],
    "포도": ["shine", "campbell", "kyoho"],
    "상추": ["lettuce_red", "lettuce_green"],
    "고추": ["redpepper", "greenpepper", "cheongyang", "shishito", "cucumberpepper", "driedpepper"],
    "파": ["greenonion", "chive"],
    "버섯": ["oyster", "enoki", "kingoyster"],
    "토마토": ["cherrytomato", "datetomato"],
    "배추": ["napa_young", "napa_baby"],
    "쌀": ["rice", "newrice", "glutinousrice", "barley"],
    "콩": ["soybean", "redbean", "mungbean"],
    "견과": ["peanut", "walnut", "almond"],
    "달걀": ["egg"],
    "닭": ["chicken"],
    "명태": ["pollock"],
    "새우": ["shrimp", "shrimpjeot"],
    "김": ["laver"],
    "멸치": ["anchovy", "fishsauce"],
    "오징어": ["squid", "driedsquid"],
    "조기": ["croaker", "gulbi"],
    "고등어": ["salted_mackerel"],
    "젓갈": ["shrimpjeot", "fishsauce"],
    "소금": ["salt"],
    "호박": ["zucchini"],
    "귤": ["tangerine"],
    "블루베리": ["blueberry"],
}

# KAMIS 가 소매가격을 조사하는 달 (2025-10 ~ 2026-09 실제 조사 기록 기준).
# 지금 조사되지 않는 품목은 앱에서 '곧 나와요'로 다음 조사 달과 작년 그때 가격을 보여 준다.
# 여기 없는 품목은 1년 내내 조사된다.
SURVEY = {
    "strawberry": [12, 1, 2, 3, 4, 5],
    "melon": [3, 4, 5, 6, 7, 8, 9],          # 참외
    "peach": [7, 8, 9],
    "persimmon": [10, 11, 12, 1, 2, 3, 4],   # 단감
    "kiwi": [10, 11, 12, 1, 2, 3, 4, 5, 6, 7, 8],
    "gizzardshad": [9, 10, 11],              # 전어
    "oyster_sea": [10, 11, 12, 1, 2, 3, 4],  # 굴
    "scallop": [10, 11, 12, 1, 2, 3, 4, 5],
    "orange": [2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    "cherry": [1, 2, 3, 5, 6, 7, 8, 9, 10],
    "kj_mustard": [10, 11, 12, 1],           # 갓 (김장 재료)
}
